# Generated by Django 2.0.5 on 2018-05-11 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('cmd', models.CharField(max_length=256)),
                ('network', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('api_port', models.PositiveIntegerField()),
                ('docker_ver', models.CharField(max_length=64)),
                ('disk_all', models.BigIntegerField()),
                ('disk_free', models.BigIntegerField()),
                ('mem_all', models.BigIntegerField()),
                ('mem_free', models.BigIntegerField()),
                ('cpu', models.CharField(max_length=64)),
                ('os', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=128)),
                ('host_to_img', models.ManyToManyField(to='dockermanage.Host')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='base_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dockermanage.Image'),
        ),
        migrations.AddField(
            model_name='container',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dockermanage.Host'),
        ),
    ]
