# Generated by Django 2.0.5 on 2018-05-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0002_auto_20180511_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_all',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_free',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_all',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_free',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(default='CentOS 7', max_length=64),
        ),
    ]
