# Generated by Django 2.0.5 on 2018-05-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0003_auto_20180511_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='host',
            name='disk_all',
        ),
        migrations.RemoveField(
            model_name='host',
            name='disk_free',
        ),
        migrations.RemoveField(
            model_name='host',
            name='mem_all',
        ),
        migrations.RemoveField(
            model_name='host',
            name='mem_free',
        ),
    ]
