# Generated by Django 2.0.5 on 2018-05-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0004_auto_20180511_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disk_all',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disk_free',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_all',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_free',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='cmd',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='docker_ver',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(default='CentOS 7', max_length=64, null=True),
        ),
    ]
