# Generated by Django 2.0.5 on 2018-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0005_auto_20180514_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disk_all',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_free',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_all',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_free',
            field=models.FloatField(null=True),
        ),
    ]
