# Generated by Django 2.0.5 on 2018-05-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0007_auto_20180515_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dockermanage.Registry'),
            preserve_default=False,
        ),
    ]
