# Generated by Django 2.0.5 on 2018-05-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockermanage', '0011_auto_20180515_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='status',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
